# SOPS правила шифрования
# Шифруем только секреты в apps/secrets/ и infrastructure/**/secrets/
# age public key подставляется в Фазе 3 после генерации ключа
creation_rules:
  - path_regex: apps/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1vq3v44x90hvv9ksqa772vnky9ydz7lht75vtv2qvswyp46g8pfmqhatmv5
  - path_regex: infrastructure/.*/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1vq3v44x90hvv9ksqa772vnky9ydz7lht75vtv2qvswyp46g8pfmqhatmv5
