# SOPS правила шифрования
# Шифруем только секреты в apps/secrets/ и infrastructure/**/secrets/
# age public key подставляется в Фазе 3 после генерации ключа
creation_rules:
  - path_regex: apps/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1l3mp8ahupqmw9kjk4gcy2z4apd0rkvps36w443ne7rvfc6u7p54qln9aeu
  - path_regex: infrastructure/.*/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1l3mp8ahupqmw9kjk4gcy2z4apd0rkvps36w443ne7rvfc6u7p54qln9aeu
