apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:Kn/AHNU=,iv:qp7bmhOZhb9FjYm25jDPR8vhPlKZ4DBmQJgDuz973kA=,tag:0FGfivB7rT1dZFsDQc3fYg==,type:str]
    admin-password: ENC[AES256_GCM,data:DX8c0/h3M2pnQBfeiUvt8+ipxi0=,iv:Q2HRASmg4mvgwLHFhpYdJL5RRm0iy2GUoBgLULE7COA=,tag:WbCt65yBiaebasINWO8VsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VVh4RS9JNk9hZjlCOWlM
            WTVRRmpSeDZBUUpqS3ozTU9FWUp1aVpWN0RZClI4eUVUT3FzMDdxajZkelVxUkRr
            K0g3Mis1c213cXFFZkFQT2JEWHQ4VzQKLS0tIE5tc2g0ZkNyaFpnTHZmVjFLdWdS
            ZHk4VFp6bS94dzB6a3Z3TEZudk42Wm8KQNwh90COxq6NOa2h8iMz7WskvG9wDCLN
            Rdo2yfKbGCSUG9TDG/Xl70PrYtMNTgGZNXomxLr78b6ugjQBX76hjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vq3v44x90hvv9ksqa772vnky9ydz7lht75vtv2qvswyp46g8pfmqhatmv5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T18:06:16Z"
    mac: ENC[AES256_GCM,data:o7KL8LJS2sdSP3StQV8+QHhP60VMN0J+Qmz/ZBfFbDyoZUHb/3hDuJgYB0k95xRBiefjGv0oBMU1P8nbn3FB/y+Icz8m5AxjxQnah+s4wjlcQXLQ1NymP0Q6TicO2Y13ESQZO9hG4Qvr35gXbXlqGYhNOCuPjsbrxSPCCX0Eh9g=,iv:TTSSnxezzb8fm5+o8oXgNm5iViVdhAp88AUw1thuXq4=,tag:fSjZ1Qqz8jDVnJxwPQ4yHA==,type:str]
    version: 3.13.1
