apiVersion: v1
kind: Secret
metadata:
    name: auth-oauth
    namespace: casego-apps
type: Opaque
stringData:
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:ASLXefZ20yZuePTIK69NDOsi8w2CbsvZbIseWUQyJE+TMST66szTy2xGBzcC89VL9Yde+sa+4HePBuSf119+FDVumai7SvQK,iv:GAEI2pBPDRg6y7jTgwkoRygEZa5/hMBrnw96mqg0Lm8=,tag:ORN+gnL4APw6Q5qgiuC5YQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTWN3VjYyTEF0RXluZkJT
            NUUxUWY0VDZ6ODcza29BSVIvVnkvV0R2UjJJCjZxbk1YR3ppY296R2VNZGltb2E4
            Vkhkay95TFAwSTRvQUdkUjV3ZGZ6UnMKLS0tIGRtOHdmdEJpSkE5a3k4b3JhK0NP
            V1RLUVdabVFtRU8rN2dlTWN4T3pSVDAKA1FIRLCV2uJUyoSVQOmZJyiXLWzqpZ4q
            GA2RDE5aBLdmfeMjp42xDJ6LiGaSCgNiUKz+sEh7CT/F/b8uJVvm7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vq3v44x90hvv9ksqa772vnky9ydz7lht75vtv2qvswyp46g8pfmqhatmv5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T20:37:15Z"
    mac: ENC[AES256_GCM,data:K0ObyB/wBHUN0F6YFFLn7MSz4aqD99Hh4u5TaymgcNdGNJ629PQB11V4tQ7dCYfQH7T416jMV0QDb1ZIvqSgOG7NxWFJ78OKqrsMSm5mmaV0WCrByAgz1TA3PI7piKDv/+A6rEM2CIpad8kua23svBm0ohWRN8zIZlGwNQ8NgJM=,iv:5dA4l4IR4D5zzpRFw9/h8XpOHf9G9UwxnZMkJudETjQ=,tag:d9G14n02kuiUHjqQTYuDng==,type:str]
    version: 3.13.1
