apiVersion: v1
kind: Secret
metadata:
    name: auth-oauth
    namespace: casego-apps
type: Opaque
stringData:
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:dGUZm2dV4sONIi48sZQn3BtKuFI/1Ro+0doBjxkfjsjTWqgTzV//+Gtg/gWFQU941G/tBPBlktPXNU7ue9v1K6NkJFBqugy5,iv:XF0g0Q2J6eDOHsHSIK9SVL0Nx1hSViI2J7uughIzuQg=,tag:1HykiatigQf/PVBa/Zw7Ug==,type:str]
sops:
    age:
        - recipient: age1l3mp8ahupqmw9kjk4gcy2z4apd0rkvps36w443ne7rvfc6u7p54qln9aeu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbUp5cDl6Q2FxZlVoeFRB
            TEFhaTlBeXBzTWd1QXFPRDh4d3NIRzhOaG04CkY1Y1psWG45KzY2cjBja2QvVWlR
            Vng0UzdJZjJNUFhEZEdBQXN1SXE3OUkKLS0tIEpNOTg2QVJVRCszTEd2QlR1SXZq
            d0RSRllCOVVyT21LbGNXMTdTV1JqY1EKPnoecicJJSdnaN+mkiwq1ZwNJWpGT68s
            xLkt3VCS9w/boVfe9DNIeHiftEuTdfRS7UHQG96wSSqqi3+21qrG9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T12:10:01Z"
    mac: ENC[AES256_GCM,data:hOFy925/klLnISqY+KvmFzF7YPCjkmHPtfc1yOczKIviZW6n44ndVZjbaqIgASDC86rDvWxFnpjSf4dILUfTodGqZVhvRgvdRnHBu+V29ovf3jyn5bJBCuNUMybLXqeHGHL0sNuh6kf+LZV4dXNaALnKj2yqwNAc+WDAF4YunKU=,iv:KgzbBu9KLOihR78fFbdyB61ZdENVR0PQ2O1fHnBHMAU=,tag:DHTKVRM418WNm7mhFZ3Sxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
