apiVersion: v1
kind: Secret
metadata:
    name: auth-oauth
    namespace: casego-apps
type: Opaque
stringData:
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:OSGeLzajhXGOgAHMQBZjWAcU+VfTavdKqnKTcBYOEeU/+6MXS+3+GloQbamGoqOweTW0178gLfTY9hk4ae4yTjJFs8CAG9ZE,iv:rrdhUb3U1ODtR0lJXqZdtq0pwkvrpVLRMjB1SU402zM=,tag:ucE7j/CMQ96Pg0c580s15g==,type:str]
sops:
    age:
        - recipient: age1l3mp8ahupqmw9kjk4gcy2z4apd0rkvps36w443ne7rvfc6u7p54qln9aeu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL3ZiUHdHM2RDeFcwRUdS
            dTZYVmdqZWtRSlRReGx3RDZhYTVReUVFK2d3CmJaN2thbE5kVXBjOExNNml3Vm05
            M1g2dWV6NWRkaVVYRFhIQlVRTEFnZlEKLS0tIHBGTHY5Mm40WnY1eUhLeGRtQzFw
            b0NEdCs2eTNveGhpS1JZOFE1TkhDVlkKlTZ2K+AzWXhICv+ecYkYlDcFSAxmrwIT
            Jkhj9RpcFLQWAuUFD2j5qyFC2oCf+Pf6Tlxc5VIo+JzdHKtxjopVAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T12:00:22Z"
    mac: ENC[AES256_GCM,data:YHR2BmAo1eFTBrYNCNVGt0YzZu6W2pMx3MtjQTICRLGkzm9hTCUnIA5Gvl+eZY8JfBDzInCNof9xDrMmRim1876mRVDmA+ZoHdYjXYK94FI4bDg3g90IoweomiraYWhqRhJ1S3mcBjEoMGoQfNKafFsnlVYH6OEOchbKaHGMf5A=,iv:S558hJ7cfo5PqMrwrgqCFTpUXZ+0iwxMAL6P/IHg7Lw=,tag:s7XCB1dqnxjkeOqaJMWgxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
