apiVersion: v1
kind: Secret
metadata:
    name: casego-llm
    namespace: casego-apps
type: Opaque
stringData:
    GIGACHAT_AUTH_KEY: ENC[AES256_GCM,data:WhXNb6+RcaGR3UnX2nGc9hEygkxcRgQ706HNbFZwAIxSuxLww/bJfQ4pVNnAgZvwhL9iQCmQ9GYbyZNtNPamEBZRyU1VgrrpQSV4QcxsTk479JsUSdtmCaiSL247kZxi6psKeQ==,iv:HrLKJ0JBu4xAmNUaIIrYn8pfUTqyGhVAb1yJFoxnxQU=,tag:Qlio1Yd+fVEW/Dexve11yA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:CciFCnOO8PuDqRmbmNrddJ9FtTY0vQZxCA==,iv:h2TLseXtNA6ZRTrJDiYCsTnlZvhpuZy9pfBCLvVLDcs=,tag:o//QVkMTFsj/fZYN+t0oQQ==,type:str]
    LLM_URL: ENC[AES256_GCM,data:v9/UAo60x76O7m/IpOFxx4yjdCgskZIppXT7,iv:C4EdVF50YAOiy2ICb1Ri6AfD8zWxdvqWUL5baryxH2g=,tag:PJrmkoZDotT5rfqDnYnE6Q==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:O4RMf/AMW88=,iv:tZEbwW5q+wLQUHR0AtFD8yuwZCx2fEEcjC/UP3rwmjI=,tag:A/sQT5HxvJ+3qVuOyXXceQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWUJEME5kT2VuSkpDdmFE
            VS9WSTltendudC9zdHZ3bFU4TVFzbzZJWGhnClhkRWJlMmZ1VGJTMEl6ZnJycG13
            RXp5dG1ETFV0bWNmcFlsVmZTZXMxUmsKLS0tIEdBbzk0cmZEaXczSUEzSVR5NUpl
            L3NWV2hSdUplMXBxckpwZUlKMC9OL1kKYA0xBWjTatv/uXI0etMH9aoMR/7vEu4l
            grKocgnOqvENQj9OB8ae0zuGSBhII/npJZoFECRfaJIRd9mBdlOR/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vq3v44x90hvv9ksqa772vnky9ydz7lht75vtv2qvswyp46g8pfmqhatmv5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T20:37:15Z"
    mac: ENC[AES256_GCM,data:HLRkGaalOV0A+mm0Ls3OWehVl23JLnIrd+NuU5WM9IgsNcBvbLxzdrZ86PFrZDYHagW6yMr7yq1j/MCpo01WeorBRUY/qScvy+L9Ms6WVZ136jmypJSmQqKf/r8bO2+FqH3hxBmHFWggt1IeQ1G1aZwXVoZTPIj+olAVPliRAo8=,iv:noph+MTUwO6e1wzViGhe/4CLpslgrBY0xNe/dKjaPaQ=,tag:fRns0QdBW+AeMWLE+xxW+Q==,type:str]
    version: 3.13.1
