apiVersion: v1
kind: Secret
metadata:
    name: casego-llm
    namespace: casego-apps
type: Opaque
stringData:
    GIGACHAT_AUTH_KEY: ENC[AES256_GCM,data:05912qhWJorI2LYzYeAOijXO0rgYjdWlH3BKRM3ruS4JyWs88cMJ,iv:qBo17IyvN18Ef8tvQJuphyXo8hVQzFZZH3pD7HpkEKo=,tag:rvC+7pSR15M8qgXgjsiwvA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:2vDZTDlwYHRlczGsklj4x1dymOV/KuLXbP5KThJsddQ=,iv:3RCzJvdChR6oJLlKWdVSVHYr5QmXUXcQHbbDtMHmgpw=,tag:9sZfaZk9Bh7uvEE6eMPoOg==,type:str]
    LLM_URL: ENC[AES256_GCM,data:JbE2R6QBsHAJct4Br6erCquHHPh5xo4YvUO1,iv:A31CNrCh4JLcRiKZeoUw2EgrdBWGcP/kDEzy+098+Ng=,tag:/ZQv5nxNpkD8Bcr+VseV0Q==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:P8+btWkI4jY=,iv:XCTw+UmsOYVOZFcEFqgHM6YerXogXZSdg++CEL33h/Y=,tag:sZDR9pNfmNyzWf7pAnyIYA==,type:str]
sops:
    age:
        - recipient: age1l3mp8ahupqmw9kjk4gcy2z4apd0rkvps36w443ne7rvfc6u7p54qln9aeu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cmZxNmFXb0ZzR1BRSUxU
            d0NQeWFaM3pKMGtQM2MxRTVWWEFkWVl4SGxVCnZVeFRsY2VTTTFqVTZhSk9tZ1pH
            ZlN1TE51Ym1UQzF1U3E0SVFtZ2tQVjQKLS0tIHR5UUVxaHNWQ2ZMWHdxb05TVmtW
            Y0p2YlF6WVI2VCtITnB0dW5nWmtsZEUKqeHe+CGTslmTQTc3ZE2j8MF8q0EHMd4K
            FgomCYCG0vwen8Ld27I/OGJCh+c56ZKMzuaWTSghxtNIVifjIanNzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T12:00:22Z"
    mac: ENC[AES256_GCM,data:LCmgyr56UOkwgz/TGsulXT7iKjy34WSk+tEQjUxzzG4Ovy5s4f8TvVktsbdht1TkfjrpF+Dljn6+GfEwQm3CClMKG/09KNt1QkWrkW/26jeHKMRG68rBN0vp3pxbkv5cqr3Maarzauq8DtUw/WrWmHNzjgLKDItJ6zLiJqktANY=,iv:mTLxgabrtE5UGnTZAAHpR2cTDY5ZKEeypBFSrZ22cPI=,tag:t+LylmuCvrt6G5TaNZ/6PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
