apiVersion: v1
kind: Secret
metadata:
    name: casego-llm
    namespace: casego-apps
type: Opaque
stringData:
    GIGACHAT_AUTH_KEY: ENC[AES256_GCM,data:XlzKSM0ZsD/4nG6K//zpkw1z6WfhFltjXdrxl2MxI6sqos6zf/ey,iv:rBrNeJiTgJvQzSnRHF9bHMoKJMjgVG9cptDQENCDK+o=,tag:3uIUoqaMZ3Y2hG0Rjg61Cg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:B6qnwsNZbGuL9nTsHSB1AYy7R6GbjPOSsaFsV0Hlazg=,iv:KeQDHiBjl/PQl+f/sZW0OtUwbhpGdMLCNI7JA2it4Yo=,tag:bd+rliq1mstJeoNIIBoJOw==,type:str]
    LLM_URL: ENC[AES256_GCM,data:4z7tPBOXH7VAHoOmzGe5HOiIYxsjsMJeor0C,iv:UNFDGtBbuGJ1H+Oo1S06GSGpXSWmSVKyfCx0Az1PW4g=,tag:4ZID+qhmqoABTP4UGO/cqA==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:DArGJBSH2wY=,iv:GrEQxXP3e4oZR77Mx9VbaL7TppvA4wDqRhnbqZv/9DI=,tag:1Cx7sJUW5hCh25GTzLxLQg==,type:str]
sops:
    age:
        - recipient: age1l3mp8ahupqmw9kjk4gcy2z4apd0rkvps36w443ne7rvfc6u7p54qln9aeu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUzF1bUFTWUNTSFNiY0E1
            dTVqUkxscFVuTWwrT3dyYVpsQXNZNGpURndvCitEalZLK1RJbW9FOU9sdnUwdTND
            Rk1qRmpJZitQVjg4aXRUVnBJOUhxTDgKLS0tIElBaUR0dWVCUXFuV01hNldZTnRh
            bEZFckVkSlVlMnNOeDlta3BIMWlEeGMKwP5/nijK7FHOMCB0KMuUybc9i5DC4dbp
            thUHrE9EGb0nlc7C6kLcMkiZj0a7P2yMSBTkdt4o6vqnviYNoa2w7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T12:10:01Z"
    mac: ENC[AES256_GCM,data:WWzGMUKofwKWmJ+NXx1DHQQ8MBam3wHclCi9Qt9JrbAzgIepDuIeyyAZXeahjolYZKvSeuMw+n8+AKdhbjrC7jAd0u11ZZ7ITJnf4Ft9Q+8uoYB+xKCg2jfravc9htt78o1/5s/C6YdBr1JNdexs7PGG3rD8t4ewj3LG9rFsbaE=,iv:+Eb7/xJ5XI0P5/avwBdHjz9SkzOoNOq3ZjSlnp8ToSQ=,tag:YKsa3jj786RjmlPgu5a2NA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
