apiVersion: v1
kind: Secret
metadata:
    name: casego-db-credentials
    namespace: casego-apps
type: Opaque
stringData:
    POSTGRES_AUTH_PASSWORD: ENC[AES256_GCM,data:NnHJsdkYQ5ZJ3LXBjRW7QUjJfsQ=,iv:aLomEY0wDe0bE/w1ud+W56R5EQjOo134PljIN/wftVk=,tag:U5B+jL/0YG564gU8YkgidQ==,type:str]
    POSTGRES_CASEGO_PASSWORD: ENC[AES256_GCM,data:y4bhkUl9Z0upaSWDfczW,iv:2l9K+JLdl8SosASMrEytZsUK0eV19psWFtskCXrayz8=,tag:SfvKSER5qnd/l60ebt9F8Q==,type:str]
    POSTGRES_CASEPROFILE_PASSWORD: ENC[AES256_GCM,data:nKdX3CKJWoQupT91iXh7qLmUhEc=,iv:ynC+2hc7vdtlPR6pU0tEjj0ZVIGh1RApTq+HnM/fFiM=,tag:3yB+0rQaEPcXAoEQackmuA==,type:str]
    POSTGRES_PAYMENT_PASSWORD: ENC[AES256_GCM,data:AIruGeTFQCnO1nt2AE3Ysw==,iv:Sxn1nwYqhdYi3muFkweERKIfgfpVZsQri9lQ4dd/uDA=,tag:i9QwEpzBBvnQk3Nksp84IA==,type:str]
    POSTGRES_PROFILE_PASSWORD: ENC[AES256_GCM,data:3ca2AvH1B+cGHjsB,iv:iEy84McKEjT3lp+y1ayvlhdJrLHm9VNNrfxwozi2ol8=,tag:L259gyyyAu6/uzSkJYKrsA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:ypimyYImOCGI4C0ounbigyuFsDcE,iv:T3uRBdRD5N2G6W9AZKhGhYWgq5G4I4TWiS+t4WyUMPo=,tag:gRy7ryuvt+MADPBJpHkY+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ3ZlcS83SmpxZGE4VHBp
            NXQ0Vi84a0poaGZjc1haK0ZyVEhFc3Y2S0YwCmRhOFBiYWdxUjg1U3hhNXZLSWhH
            b3dpRHNxQkhjTkh6dWZxRnhGUjJVMGcKLS0tIC8vTk1zV3NjV3ZIUzF1ejM4UHNm
            WmppT0w5R09WdUI5UjFXMkV1R05kdkUKg7yWymm03rpczwxm6OxirG9q165MJonH
            TvXIdEfZoeBTuuVOhHBFbBg0RpuLlMaUMWMEl7ljlGMbLTx0aMzSIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vq3v44x90hvv9ksqa772vnky9ydz7lht75vtv2qvswyp46g8pfmqhatmv5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T13:00:40Z"
    mac: ENC[AES256_GCM,data:g5he46YtnmSVraGNm1VZXcGCdhBMpK/QB1+RlaNGU369xkGfpux91Zvqc7xo3GNUE7pgOmDSxNVO6v/Vsga2g7GR5ZcLF/YA6/w1FokAd1Hk2xa97AnFGsxht6eATR1eLZQZIU1rhyloh2hvuQUCgc5rcxogaI/unQa05f2z4Qg=,iv:0R/xWGKLkhF7I+5bI0HdVA9nWRzbjR0k0rp8zet6M+Y=,tag:uoSOKSc6dsKQiHl0mbT19Q==,type:str]
    version: 3.13.1
