apiVersion: apps/v1
kind: Deployment
metadata:
  name: caseprofile
  namespace: casego-apps
  labels:
    app: caseprofile
spec:
  selector:
    matchLabels:
      app: caseprofile
  template:
    metadata:
      labels:
        app: caseprofile
    spec:
      initContainers:
        - name: copy-migrations
          image: ghcr.io/sewaustav/casego-caseprofile:main-1781351499-bed3ed1aeb27d9d4a5f5da524b63d597d8b603e3 # {"$imagepolicy": "flux-system:casego-caseprofile"}
          command: ["sh", "-c", "cp -r /app/migrations/. /m/"]
          volumeMounts:
            - name: migrations
              mountPath: /m
        - name: migrate
          image: migrate/migrate:v4.19.1
          args:
            - -path=/m
            - -database=postgres://caseprofile_user:$(POSTGRES_PASSWORD)@postgres-caseprofile:5432/caseprofile_db?sslmode=disable
            - up
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: casego-db-credentials
                  key: POSTGRES_CASEPROFILE_PASSWORD
          volumeMounts:
            - name: migrations
              mountPath: /m
      containers:
        - name: caseprofile
          image: ghcr.io/sewaustav/casego-caseprofile:main-1781351499-bed3ed1aeb27d9d4a5f5da524b63d597d8b603e3 # {"$imagepolicy": "flux-system:casego-caseprofile"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
            - name: grpc
              containerPort: 50051
          env:
            - name: POSTGRES_HOST
              value: postgres-caseprofile
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: caseprofile_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: casego-db-credentials
                  key: POSTGRES_CASEPROFILE_PASSWORD
            - name: POSTGRES_DB
              value: caseprofile_db
            - name: PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: jwt-public-key
                  key: PUBLIC_KEY        
            - name: AUTH_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: jwt-public-key
                  key: PUBLIC_KEY
            - name: CASEGO_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: jwt-public-key
                  key: PUBLIC_KEY
            - name: GIN_MODE
              value: release
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: migrations
          emptyDir: {}
