apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: caseprofile
  namespace: casego-apps
  labels:
    app: caseprofile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: caseprofile
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
