apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: casego-apps
  labels:
    app: profile
spec:
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: ghcr.io/sewaustav/casego-profile:main-e53da2d11c6196385c42da11a329b3f9812b4093 # {"$imagepolicy": "flux-system:casego-profile"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: postgres-profile
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: dev_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: casego-db-credentials
                  key: POSTGRES_PROFILE_PASSWORD
            - name: POSTGRES_DB
              value: app_db
            - name: PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: jwt-public-key
                  key: PUBLIC_KEY
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: tls
              mountPath: /root/certs
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: profile-server-tls
