apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-public-key
  namespace: casego-apps
data:
  PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzn6VujVO1m0eQqoS1ThX\n7jq+AXUj1W0ojKz+MtgUJacV7IKm8QlT1xjOJfebot+iLBkVR+un9OXdLrA3glOC\n/XJBVmy3obHQ8IBp9/IFyACmJVwHajuJTKh5IlmeGcIYWD3z2jEG6IGHyT/oG2TL\nf6AEzOnp655kyNOA4PIrm8WUrfvy08vV4EiQYrGYRrzVzR85nsQmCyssoPtvJaS2\n5ZLlNDMulVn7gBgjPMSD4wEaaHv7vXf101TfQXP+P8LQoKgcnWtrCQwMG9M8Mt2G\nR1t9ZEPetWoBwJ8DSeZur3jMykZWB4Ddo1cklyO7Fsbpi+wYR4kCa74iUC6A2R42\ndwIDAQAB\n-----END PUBLIC KEY-----"
