apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: casego-apps
  labels:
    app: payment
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      initContainers:
        - name: copy-migrations
          image: ghcr.io/sewaustav/casego-payment:main-1781964753-36eff90217b1a445e2acfd5cc9f566913dfc17ca # {"$imagepolicy": "flux-system:casego-payment"}
          command: ["sh", "-c", "cp -r /app/migrations/. /m/"]
          volumeMounts:
            - name: migrations
              mountPath: /m
        - name: migrate
          image: migrate/migrate:v4.19.1
          args:
            - -path=/m
            - -database=postgres://payment_user:$(POSTGRES_PASSWORD)@postgres-payment:5432/payment_db?sslmode=disable
            - up
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: casego-db-credentials
                  key: POSTGRES_PAYMENT_PASSWORD
          volumeMounts:
            - name: migrations
              mountPath: /m
      containers:
        - name: payment
          image: ghcr.io/sewaustav/casego-payment:main-1781964753-36eff90217b1a445e2acfd5cc9f566913dfc17ca # {"$imagepolicy": "flux-system:casego-payment"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8085
            - name: grpc
              containerPort: 50052
          env:
            - name: POSTGRES_HOST
              value: postgres-payment
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: payment_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: casego-db-credentials
                  key: POSTGRES_PAYMENT_PASSWORD
            - name: POSTGRES_DB
              value: payment_db
            - name: PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: jwt-public-key
                  key: PUBLIC_KEY
            - name: GIN_MODE
              value: release
          volumeMounts:
            - name: tls
              mountPath: /app/certs
              readOnly: true
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: tls
          secret:
            secretName: payment-server-tls
        - name: migrations
          emptyDir: {}
